apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: forum-app 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: forum-app 
  template: 
    metadata: 
      labels: 
        app: forum-app 
    spec: 
      containers: 
        - name: forum-app 
          image: afangndong/forum-app:latest 
          ports: 
            - containerPort: 5000
